name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev typescript@5.3.3 @types/react@18.2.64 @types/node@20.11.25 @types/react-dom@18.2.21

      - name: Build
        run: npm run build

      - name: Add .nojekyll file
        run: |
          touch out/.nojekyll
          cp README.md out/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages 